name: ifirmhub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  android_intent_plus: ^6.0.0
  clipboard: ^3.0.14
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  # flutter_local_notifications: ^21.0.0
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  open_settings_plus: ^0.4.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  go_router_builder: ^4.2.0
  riverpod_generator: ^3.0.3
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/icon/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#141754"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#3f46cc"
    theme_color: "#3f46cc"